export const deckGuides = [
	{
		kind: "deck",
		title: "Portgas.D.Ace OP16 Deck Guide",
		leader: "Portgas.D.Ace",
		code: "OP16",
		formatLabel: "OP16 Format",
		summary: "Decklist, mulligan priorities, curve guide, tech cards, matchup notes, and gameplay tips for Portgas.D.Ace OP16.",
		month: "June",
		href: "/deck-guides/portgas-d-ace-op16/",
		imageSrc: "/assets/guides/Ace-op16.png",
		imageAlt: "Portgas.D.Ace OP16 guide icon",
		aliases: ["portgas d ace", "portgasdace", "portgas ace", "ace", "op16 ace", "red ace"],
		tags: ["op16", "red", "whitebeard pirates"],
	},
	{
		kind: "deck",
		title: "Portgas.D.Ace OP13 Deck Guide",
		leader: "Portgas.D.Ace",
		code: "OP13",
		formatLabel: "OP16 Format",
		summary: "Decklist, mulligan priorities, curve guide, tech cards, matchup notes, and OP16 gameplay tips.",
		month: "June",
		href: "/deck-guides/portgas-d-ace-op13/",
		imageSrc: "/assets/guides/portgas-d-ace-op13.png",
		imageAlt: "Portgas.D.Ace OP13 guide icon",
		aliases: ["portgas d ace", "portgasdace", "portgas ace", "ace"],
		tags: ["op13", "op16", "red", "whitebeard"],
	},
	{
		kind: "deck",
		title: "Sengoku OP16 Deck Guide",
		leader: "Sengoku",
		code: "OP16",
		formatLabel: "OP16 Format",
		summary: "Decklist, key cards, turn curve, replacement options, matchup notes, and core deck fundamentals.",
		month: "June",
		href: "/deck-guides/sengoku-op16/",
		imageSrc: "/assets/guides/Sengoku-op16.png",
		imageAlt: "Sengoku OP16 guide icon",
		aliases: ["sengoku", "op16 sengoku", "purple sengoku", "navy sengoku", "admiral sengoku"],
		tags: ["op16", "purple", "navy", "admiral"],
	},
	{
		kind: "deck",
		title: "Yamato OP16 Deck Guide",
		leader: "Yamato",
		code: "OP16",
		formatLabel: "OP16 Format",
		summary: "Decklist, mulligan priorities, curve guide, tech cards, matchup notes, and OP16 gameplay tips.",
		month: "June",
		href: "/deck-guides/yamato-op16/",
		imageSrc: "/assets/guides/yamato-op16.png",
		imageAlt: "Yamato OP16 guide icon",
		aliases: ["yamato", "op16 yamato", "black yamato", "wano yamato"],
		tags: ["op16", "black", "land of wano", "wano"],
	},
	{
		kind: "deck",
		title: "Donquixote Rosinante OP12 Deck Guide",
		leader: "Donquixote Rosinante",
		code: "OP12",
		formatLabel: "OP16 Format",
		summary: "Decklist, combos, options, matchup notes, mirror tips, and conclusion for OP12 Rosinante in OP16.",
		month: "June",
		href: "/deck-guides/rosinante-op12/",
		imageSrc: "/assets/guides/rosinante-op12.png",
		imageAlt: "Rosinante OP12 guide icon",
		aliases: ["donquixote rosinante", "rosinante", "corazon", "op12 rosinante", "purple yellow rosinante"],
		tags: ["op12", "op16", "purple", "yellow", "law", "navy"],
	},
	{
		kind: "deck",
		title: "Buggy OP16 Deck Guide",
		leader: "Buggy",
		code: "OP16",
		formatLabel: "OP16 Format",
		summary: "Decklist, mulligan priorities, a going-second curve guide, tech cards, matchup notes, and gameplay tips for Buggy OP16.",
		month: "June",
		href: "/deck-guides/buggy-op16/",
		imageSrc: "/assets/guides/Buggy%20op16.png",
		imageAlt: "Buggy OP16 guide icon",
		aliases: ["buggy", "op16 buggy", "blue buggy", "impel down buggy", "clown buggy"],
		tags: ["op16", "blue", "impel down", "buggy pirates"],
	},
	{
		kind: "deck",
		title: "Monkey.D.Luffy OP16 Preview Deck Guide",
		leader: "Monkey.D.Luffy",
		code: "OP16",
		formatLabel: "OP16 Format",
		summary: "Preview guide with an early decklist idea, key Impel Down spoilers, the old-set shell, and early strengths and weaknesses.",
		month: "May",
		href: "/deck-guides/monkey-d-luffy-op16/",
		imageSrc: "/assets/guides/Luffy%20op16.png",
		imageAlt: "Monkey.D.Luffy OP16 guide icon",
		aliases: ["monkey d luffy", "monkeydluffy", "luffy", "op16 luffy", "green blue luffy", "impel down luffy"],
		tags: ["op16", "green", "blue", "impel down", "straw hat crew", "preview"],
	},
	{
		kind: "deck",
		title: "Marshall.D.Teach OP16 Deck Guide",
		leader: "Marshall.D.Teach",
		code: "OP16",
		formatLabel: "OP16 Format",
		summary: "Decklist, mulligan priorities, a curve guide, tech cards, matchup notes, and gameplay tips for Marshall.D.Teach OP16.",
		month: "June",
		href: "/deck-guides/marshall-d-teach-op16/",
		imageSrc: "/assets/guides/Teach-op16.png",
		imageAlt: "Marshall.D.Teach OP16 guide icon",
		aliases: ["marshall d teach", "marshaldteach", "teach", "blackbeard", "op16 teach", "black yellow teach"],
		tags: ["op16", "black", "yellow", "blackbeard pirates"],
	},
	{
		kind: "deck",
		title: "Monkey.D.Luffy OP15 Deck Guide",
		leader: "Monkey.D.Luffy",
		code: "OP15",
		formatLabel: "OP15 Format",
		summary: "Decklist, replacement options, mulligan priorities, curve plans, tips, and matchup notes.",
		month: "May",
		href: "/deck-guides/monkey-d-luffy-op15/",
		imageSrc: "/assets/guides/monkey-d-luffy-op15.png",
		imageAlt: "Monkey.D.Luffy OP15 guide icon",
		aliases: [
			"monkey d luffy",
			"monkeydluffy",
			"luffy",
			"op15 luffy",
			"yellow luffy",
			"campaign luffy",
			"campana luffy",
		],
		tags: ["op15", "yellow", "sky island", "campaign", "heal", "trigger"],
	},
	{
		kind: "deck",
		title: "Monkey.D.Luffy ST14 Deck Guide",
		leader: "Monkey.D.Luffy",
		code: "ST14",
		formatLabel: "OP15 Format",
		summary: "Decklist, tech choices, curve checkpoints, mulligan priorities, and matchup notes.",
		month: "May",
		href: "/deck-guides/monkey-d-luffy-st14/",
		imageSrc: "/assets/guides/Luffy%20st14.png",
		imageAlt: "Monkey.D.Luffy ST14 guide icon",
		aliases: ["monkey d luffy", "monkeydluffy", "luffy", "st14 luffy", "black luffy", "trash luffy"],
		tags: ["st14", "black", "straw hat", "trash", "op15"],
	},
	{
		kind: "deck",
		title: "Monkey.D.Luffy EB02 Deck Guide",
		leader: "Monkey.D.Luffy",
		code: "EB02",
		formatLabel: "OP15 Format",
		summary: "Decklist, curve checkpoints, mulligan priorities, tips, and matchup notes.",
		month: "May",
		href: "/deck-guides/monkey-d-luffy-eb02/",
		imageSrc: "/assets/guides/Monkey D. Luffy EB02-010.png",
		imageAlt: "Monkey.D.Luffy EB02 guide icon",
		aliases: ["monkey d luffy", "monkeydluffy", "luffy", "eb02 luffy", "green purple luffy"],
		tags: ["eb02", "green", "purple", "straw hat"],
	},
	{
		kind: "deck",
		title: "Sanji OP12 Deck Guide",
		leader: "Sanji",
		code: "OP12",
		formatLabel: "OP15 Format",
		summary: "Decklist, curve checkpoints, mulligan priorities, options, and matchup notes.",
		month: "May",
		href: "/deck-guides/sanji-op12/",
		imageSrc: "/assets/guides/sanji-op12.png",
		imageAlt: "Sanji OP12 guide icon",
		aliases: ["sanji"],
		tags: ["op12", "blue", "yellow", "germa"],
	},
	{
		kind: "deck",
		title: "Enel OP15 Deck Guide",
		leader: "Enel",
		code: "OP15",
		formatLabel: "OP15 Format",
		summary: "Decklist, curve checkpoints, mulligan priorities, options, and matchup notes.",
		month: "April",
		href: "/deck-guides/enel-op15/",
		imageSrc: "/assets/guides/enel-op15.png",
		imageAlt: "Enel OP15 guide icon",
		aliases: ["enel"],
		tags: ["op15", "yellow", "skypiea"],
	},
	{
		kind: "deck",
		title: "Lucy OP15 Deck Guide",
		leader: "Lucy",
		code: "OP15",
		formatLabel: "OP15 Format",
		summary: "Decklist, curve checkpoints, mulligan priorities, options, and matchup notes.",
		month: "April",
		href: "/deck-guides/lucy-op15/",
		imageSrc: "/assets/guides/lucy-op15.png",
		imageAlt: "Lucy OP15 guide icon",
		aliases: ["lucy"],
		tags: ["op15", "dressrosa", "sabo"],
	},
	{
		kind: "deck",
		title: "Nami OP11 Deck Guide",
		leader: "Nami",
		code: "OP11",
		formatLabel: "OP15 Format",
		summary: "Decklist, curve checkpoints, mulligan priorities, options, and matchup notes.",
		month: "April",
		href: "/deck-guides/nami-op11/",
		imageSrc: "/assets/guides/nami-op11.png",
		imageAlt: "Nami OP11 guide icon",
		aliases: ["nami"],
		tags: ["op11", "eb03", "blue", "straw hat"],
	},
	{
		kind: "deck",
		title: "Jinbe OP14 Deck Guide",
		leader: "Jinbe",
		code: "OP14",
		formatLabel: "OP14 Format",
		summary: "Decklist, curve checkpoints, mulligan priorities, options, and matchup notes.",
		month: "March",
		href: "/deck-guides/jinbe-op14/",
		imageSrc: "/assets/guides/jinbe-op14.png",
		imageAlt: "Jinbe OP14 guide icon",
		aliases: ["jinbe", "jinbei", "jimbei"],
		tags: ["op14", "blue", "fishman", "fish-man"],
	},
	{
		kind: "deck",
		title: "Dracule Mihawk OP14 Deck Guide",
		leader: "Dracule Mihawk",
		code: "OP14",
		formatLabel: "OP14 Format",
		summary: "Decklist, curve checkpoints, mulligan priorities, options, and matchup notes.",
		month: "March",
		href: "/deck-guides/dracule-mihawk-op14/",
		imageSrc: "/assets/guides/dracule-mihawk-op14.png",
		imageAlt: "Dracule Mihawk OP14 guide icon",
		aliases: ["dracule mihawk", "mihawk", "dracule"],
		tags: ["op14", "green", "slash", "freeze"],
	},
	{
		kind: "deck",
		title: "Trafalgar Law OP14 Deck Guide",
		leader: "Trafalgar Law",
		code: "OP14",
		formatLabel: "OP14 Format",
		summary: "Decklist, curve checkpoints, mulligan priorities, options, and matchup notes.",
		month: "March",
		href: "/deck-guides/trafalgar-law-op14/",
		imageSrc: "/assets/guides/trafalgar-law-op14.png",
		imageAlt: "Trafalgar Law OP14 guide icon",
		aliases: ["trafalgar law", "trafalgar", "law", "traf law"],
		tags: ["op14", "red", "supernova"],
	},
	{
		kind: "deck",
		title: "Monkey.D.Luffy ST29 Deck Guide",
		leader: "Monkey.D.Luffy",
		code: "ST29",
		formatLabel: "OP14 Format",
		summary: "Decklist, curve checkpoints, mulligan priorities, options, and matchup notes.",
		month: "March",
		href: "/deck-guides/monkey-d-luffy-st29/",
		imageSrc: "/assets/guides/monkey-d-luffy-st29.png",
		imageAlt: "Monkey.D.Luffy ST29 guide icon",
		aliases: ["monkey d luffy", "monkeydluffy", "luffy", "st29 luffy"],
		tags: ["st29", "yellow", "trigger"],
	},
	{
		kind: "deck",
		title: "Crocodile OP14 Deck Guide",
		leader: "Crocodile",
		code: "OP14",
		formatLabel: "OP14 Format",
		summary: "Decklist, curve checkpoints, mulligan priorities, options, and matchup notes.",
		month: "March",
		href: "/deck-guides/crocodile-op14/",
		imageSrc: "/assets/guides/crocodile-op14.png",
		imageAlt: "Crocodile OP14 guide icon",
		aliases: ["crocodile"],
		tags: ["op14", "black", "baroque works"],
	},
	{
		kind: "deck",
		title: "Boa Hancock OP14 Deck Guide",
		leader: "Boa Hancock",
		code: "OP14",
		formatLabel: "OP14 Format",
		summary: "Decklist, curve checkpoints, mulligan priorities, options, and matchup notes.",
		month: "March",
		href: "/deck-guides/boa-hancock-op14/",
		imageSrc: "/assets/guides/boa-hancock-op14.png",
		imageAlt: "Boa Hancock OP14 guide icon",
		aliases: ["boa hancock", "boa", "hancock"],
		tags: ["op14", "blue", "amazon lily"],
	},
] as const;

export const visibleDeckGuides = deckGuides.filter((guide) => !guide.hidden);

export const beginnerGuides = [
	{
		kind: "beginner",
		title: "How to Choose a Deck?",
		leader: "Beginner Guides",
		code: "Playstyle",
		month: "Beginner",
		href: "/beginner-guides/how-to-choose-a-deck/",
		imageSrc: "/assets/beginner-guides/how-to-choose-a-deck.svg",
		imageAlt: "How to choose a deck guide cover",
		aliases: [
			"how to choose a deck",
			"choose a deck",
			"which deck should i play",
			"deck colors",
			"color guide",
			"playstyle guide",
		],
		tags: [
			"beginner",
			"beginner guides",
			"red aggro",
			"green rest",
			"blue draw",
			"purple don",
			"black control",
			"yellow trigger",
		],
	},
	{
		kind: "beginner",
		title: "Complete One Piece TCG Rules",
		leader: "Beginner Guides",
		code: "Rules",
		month: "Beginner",
		href: "/beginner-guides/complete-rules/",
		imageSrc: "/assets/beginner-guides/complete-rules.png",
		imageAlt: "Complete rules guide cover",
		aliases: ["complete rules", "full rules", "one piece rules", "tcg rules"],
		tags: ["beginner", "rules", "official rules", "complete rulebook"],
	},
	{
		kind: "beginner",
		title: "Simplified Rules Overview",
		leader: "Beginner Guides",
		code: "Rules",
		month: "Beginner",
		href: "/beginner-guides/simplified-rules/",
		imageSrc: "/assets/beginner-guides/simplified-rules.png",
		imageAlt: "Simplified rules guide cover",
		aliases: ["simplified rules", "rules overview", "quick rules", "simple rules"],
		tags: ["beginner", "rules", "summary", "quick start"],
	},
] as const;

const buildGuideSearchIndex = (guides) =>
	guides.map((guide) => ({
		...guide,
		primaryText: [guide.title, guide.leader, guide.code, ...(guide.aliases ?? [])].join(" "),
		searchText: [guide.title, guide.leader, guide.code, guide.month, ...(guide.aliases ?? []), ...(guide.tags ?? [])].join(
			" ",
		),
		secondaryText: [guide.code, guide.month, ...(guide.tags ?? [])].join(" "),
	}));

export const guideSearchIndex = [
	...buildGuideSearchIndex(visibleDeckGuides),
	...buildGuideSearchIndex(beginnerGuides),
];
