export const deckGuides = [
	{
		kind: "deck",
		title: "Enel OP15 Deck Guide",
		leader: "Enel",
		code: "OP15",
		month: "April",
		href: "/deck-guides/enel-op15",
		imageSrc: "/assets/guides/enel-op15.png",
		imageAlt: "Enel OP15 guide icon",
		aliases: ["enel"],
		tags: ["op15", "yellow", "skypiea"],
	},
	{
		kind: "deck",
		title: "Lucy OP15 Deck Guide",
		leader: "Lucy",
		code: "OP15",
		month: "April",
		href: "/deck-guides/lucy-op15",
		imageSrc: "/assets/guides/lucy-op15.png",
		imageAlt: "Lucy OP15 guide icon",
		aliases: ["lucy"],
		tags: ["op15", "dressrosa", "sabo"],
	},
	{
		kind: "deck",
		title: "Nami OP11 Deck Guide",
		leader: "Nami",
		code: "OP11",
		month: "April",
		href: "/deck-guides/nami-op11",
		imageSrc: "/assets/guides/nami-op11.png",
		imageAlt: "Nami OP11 guide icon",
		aliases: ["nami"],
		tags: ["op11", "eb03", "blue", "straw hat"],
	},
	{
		kind: "deck",
		title: "Rosinante OP12 Deck Guide",
		leader: "Rosinante",
		code: "OP12",
		month: "April",
		href: "/deck-guides/rosinante-op12",
		imageSrc: "/assets/guides/rosinante-op12.png",
		imageAlt: "Rosinante OP12 guide icon",
		aliases: ["rosinante", "corazon"],
		tags: ["op12", "green", "law"],
	},
	{
		kind: "deck",
		title: "Jinbe OP14 Deck Guide",
		leader: "Jinbe",
		code: "OP14",
		month: "March",
		href: "/deck-guides/jinbe-op14",
		imageSrc: "/assets/guides/jinbe-op14.png",
		imageAlt: "Jinbe OP14 guide icon",
		aliases: ["jinbe", "jinbei", "jimbei"],
		tags: ["op14", "blue", "fishman", "fish-man"],
	},
	{
		kind: "deck",
		title: "Dracule Mihawk OP14 Deck Guide",
		leader: "Dracule Mihawk",
		code: "OP14",
		month: "March",
		href: "/deck-guides/dracule-mihawk-op14",
		imageSrc: "/assets/guides/dracule-mihawk-op14.png",
		imageAlt: "Dracule Mihawk OP14 guide icon",
		aliases: ["dracule mihawk", "mihawk", "dracule"],
		tags: ["op14", "green", "slash", "freeze"],
	},
	{
		kind: "deck",
		title: "Trafalgar Law OP14 Deck Guide",
		leader: "Trafalgar Law",
		code: "OP14",
		month: "March",
		href: "/deck-guides/trafalgar-law-op14",
		imageSrc: "/assets/guides/trafalgar-law-op14.png",
		imageAlt: "Trafalgar Law OP14 guide icon",
		aliases: ["trafalgar law", "trafalgar", "law", "traf law"],
		tags: ["op14", "red", "supernova"],
	},
	{
		kind: "deck",
		title: "Monkey.D.Luffy ST29 Deck Guide",
		leader: "Monkey.D.Luffy",
		code: "ST29",
		month: "March",
		href: "/deck-guides/monkey-d-luffy-st29",
		imageSrc: "/assets/guides/monkey-d-luffy-st29.png",
		imageAlt: "Monkey.D.Luffy ST29 guide icon",
		aliases: ["monkey d luffy", "monkeydluffy", "luffy", "st29 luffy"],
		tags: ["st29", "yellow", "trigger"],
	},
	{
		kind: "deck",
		title: "Crocodile OP14 Deck Guide",
		leader: "Crocodile",
		code: "OP14",
		month: "March",
		href: "/deck-guides/crocodile-op14",
		imageSrc: "/assets/guides/crocodile-op14.png",
		imageAlt: "Crocodile OP14 guide icon",
		aliases: ["crocodile"],
		tags: ["op14", "black", "baroque works"],
	},
	{
		kind: "deck",
		title: "Boa Hancock OP14 Deck Guide",
		leader: "Boa Hancock",
		code: "OP14",
		month: "March",
		href: "/deck-guides/boa-hancock-op14",
		imageSrc: "/assets/guides/boa-hancock-op14.png",
		imageAlt: "Boa Hancock OP14 guide icon",
		aliases: ["boa hancock", "boa", "hancock"],
		tags: ["op14", "blue", "amazon lily"],
	},
	{
		kind: "deck",
		title: "Portgas.D.Ace OP13 Deck Guide",
		leader: "Portgas.D.Ace",
		code: "OP13",
		month: "May",
		href: "/deck-guides/portgas-d-ace-op13",
		imageSrc: "/assets/guides/portgas-d-ace-op13.png",
		imageAlt: "Portgas.D.Ace OP13 guide icon",
		aliases: ["portgas d ace", "portgasdace", "portgas ace", "ace"],
		tags: ["op13", "red", "whitebeard"],
	},
] as const;

export const beginnerGuides = [
	{
		kind: "beginner",
		title: "How to Choose a Deck?",
		leader: "Beginner Guides",
		code: "Playstyle",
		month: "Beginner",
		href: "/beginner-guides/how-to-choose-a-deck",
		imageSrc: "/assets/beginner-guides/how-to-choose-a-deck.svg",
		imageAlt: "How to choose a deck guide cover",
		aliases: [
			"how to choose a deck",
			"choose a deck",
			"which deck should i play",
			"deck colors",
			"color guide",
			"playstyle guide",
		],
		tags: [
			"beginner",
			"beginner guides",
			"red aggro",
			"green rest",
			"blue draw",
			"purple don",
			"black control",
			"yellow trigger",
		],
	},
	{
		kind: "beginner",
		title: "Complete One Piece TCG Rules",
		leader: "Beginner Guides",
		code: "Rules",
		month: "Beginner",
		href: "/beginner-guides/complete-rules",
		imageSrc: "/assets/beginner-guides/complete-rules.png",
		imageAlt: "Complete rules guide cover",
		aliases: ["complete rules", "full rules", "one piece rules", "tcg rules"],
		tags: ["beginner", "rules", "official rules", "complete rulebook"],
	},
	{
		kind: "beginner",
		title: "Simplified Rules Overview",
		leader: "Beginner Guides",
		code: "Rules",
		month: "Beginner",
		href: "/beginner-guides/simplified-rules",
		imageSrc: "/assets/beginner-guides/simplified-rules.png",
		imageAlt: "Simplified rules guide cover",
		aliases: ["simplified rules", "rules overview", "quick rules", "simple rules"],
		tags: ["beginner", "rules", "summary", "quick start"],
	},
] as const;

const buildGuideSearchIndex = (guides) =>
	guides.map((guide) => ({
		...guide,
		primaryText: [guide.title, guide.leader, guide.code, ...(guide.aliases ?? [])].join(" "),
		searchText: [guide.title, guide.leader, guide.code, guide.month, ...(guide.aliases ?? []), ...(guide.tags ?? [])].join(
			" ",
		),
		secondaryText: [guide.code, guide.month, ...(guide.tags ?? [])].join(" "),
	}));

export const guideSearchIndex = [
	...buildGuideSearchIndex(deckGuides),
	...buildGuideSearchIndex(beginnerGuides),
];
